---
style: github
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://github.com/netdata/kernel-collector
options:
  commits:
    filters:
      Type:
        - Add
        - Fix
        - Document
        - Refactor
  commit_groups:
    title_maps:
      Add: Features
      Fix: Bug Fixes
      Document: Documentation
      refactor: Code Refactoring
  header:
    pattern: "^((\\w+)\\s.*)$"
    pattern_maps:
      - Subject
      - Type
  notes:
    keywords:
      - BREAKING CHANGE
